package metadata

import (
	"encoding/json"
	"fmt"
)

type MetadataModel struct {
	// ID is auto-generated by the chaincode's internal counter (_metadata_id_counter).
	// It is read-only: never sent on create, always populated on read responses.
	ID            uint64 `json:"id,omitempty"`
	PatientID     string `json:"patient_id"`
	AssetID       string `json:"asset_id"`
	ZKPProof      string `json:"zkp_proof"`
	Name          string `json:"name"`
	Value         string `json:"value"`
	Version       string `json:"version"`
	Owner         string `json:"owner"`
	Rights        string `json:"rights"`
	TermsOfAccess string `json:"terms_of_access"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
	CreatedBy     string `json:"created_by"`
	UpdatedBy     string `json:"updated_by"`
}

type flexibleString string

func (fs *flexibleString) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		*fs = ""
		return nil
	}
	var str string
	if err := json.Unmarshal(data, &str); err == nil {
		*fs = flexibleString(str)
		return nil
	}

	var num json.Number
	if err := json.Unmarshal(data, &num); err == nil {
		*fs = flexibleString(num.String())
		return nil
	}

	return fmt.Errorf("failed to unmarshal flexibleString: %s", string(data))
}

func (m *MetadataModel) UnmarshalJSON(data []byte) error {
	type metadataAlias MetadataModel
	aux := struct {
		metadataAlias
		PatientIDFlexible flexibleString `json:"patient_id"`
		AssetIDFlexible   flexibleString `json:"asset_id"`
		TermsOfAccessCamel string         `json:"termsOfAccess"`
		CreatedAtCamel     string         `json:"createdAt"`
		UpdatedAtCamel     string         `json:"updatedAt"`
		CreatedByCamel     string         `json:"createdBy"`
		UpdatedByCamel     string         `json:"updatedBy"`
	}{}

	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}

	*m = MetadataModel(aux.metadataAlias)
	m.PatientID = string(aux.PatientIDFlexible)
	m.AssetID = string(aux.AssetIDFlexible)

	if m.TermsOfAccess == "" {
		m.TermsOfAccess = aux.TermsOfAccessCamel
	}
	if m.CreatedAt == "" {
		m.CreatedAt = aux.CreatedAtCamel
	}
	if m.UpdatedAt == "" {
		m.UpdatedAt = aux.UpdatedAtCamel
	}
	if m.CreatedBy == "" {
		m.CreatedBy = aux.CreatedByCamel
	}
	if m.UpdatedBy == "" {
		m.UpdatedBy = aux.UpdatedByCamel
	}

	return nil
}

// MetadataHistoryEntry represents one record in the audit trail returned by
// the GetMetadataAuditoryById chaincode function.
type MetadataHistoryEntry struct {
	TxID      string        `json:"tx_id"`
	Timestamp string        `json:"timestamp"`
	IsDelete  bool          `json:"is_delete"`
	Value     MetadataModel `json:"value"`
}
