package metadata

import "time"

type MetadataModel struct {
	// ID is auto-generated by the chaincode's internal counter (_metadata_id_counter).
	// It is read-only: never sent on create, always populated on read responses.
	ID            uint64 `json:"id,omitempty"`
	PatientID     int    `json:"patient_id"`
	AssetID       int    `json:"asset_id"`
	ZKPProof      string `json:"zkp_proof"`
	Name          string `json:"name"`
	Value         string `json:"value"`
	Version       string `json:"version"`
	Owner         string `json:"owner"`
	Rights        string `json:"rights"`
	TermsOfAccess string `json:"terms_of_access"`
	// Dates are stored as RFC3339 strings, matching the chaincode's on-chain representation.
	CreatedAt string  `json:"created_at,omitempty"`
	UpdatedAt string  `json:"updated_at,omitempty"`
	DeletedAt *string `json:"deleted_at,omitempty"`
	CreatedBy string  `json:"created_by"`
	UpdatedBy string  `json:"updated_by"`
}

// nowRFC3339 returns the current UTC time formatted as RFC3339.
func nowRFC3339() string {
	return time.Now().UTC().Format(time.RFC3339)
}

// MetadataHistoryEntry represents one record in the audit trail returned by
// the GetMetadataAuditoryById chaincode function.
type MetadataHistoryEntry struct {
	TxID      string        `json:"tx_id"`
	Timestamp string        `json:"timestamp"`
	IsDelete  bool          `json:"is_delete"`
	Value     MetadataModel `json:"value"`
}
