package metadata

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/hyperledger/fabric-gateway/pkg/client"
	"github.com/silvasilas99/entruster/audit"
	"github.com/silvasilas99/entruster/elasticsearch"
	"github.com/silvasilas99/entruster/utils"
)

// CreateMetadataHandler handles POST /api/metadata/
//
//	@Summary		Register metadata on the blockchain
//	@Description	Submits a new metadata asset to the Hyperledger Fabric ledger. The asset ID is auto-generated by the chaincode.
//	@Tags			metadata
//	@Accept			json
//	@Produce		json
//	@Param			metadata	body		MetadataModel	true	"Metadata payload (patient_id and asset_id must be numeric strings)"
//	@Success		201			{object}	utils.SuccessResponse{data=map[string]string}
//	@Failure		400			{object}	utils.ErrorResponse
//	@Failure		500			{object}	utils.ErrorResponse
//	@Router			/metadata/ [post]
func CreateMetadataHandler(contract *client.Contract, observer *MetadataObserver) gin.HandlerFunc {
	return func(c *gin.Context) {
		var req MetadataModel
		if err := c.ShouldBindJSON(&req); err != nil {
			utils.SendError(c, http.StatusBadRequest, "Invalid request body. Check the required fields and their types.")
			return
		}
		if err := CreateMetadata(contract, req, observer); err != nil {
			utils.SendError(c, http.StatusInternalServerError, err.Error())
			return
		}
		utils.SendSuccess(c, "Metadata registered on blockchain", gin.H{
			"patient_id": req.PatientID,
			"asset_id":   req.AssetID,
		})
	}
}

// GetAllMetadataHandler handles GET /api/metadata/
//
//	@Summary		List all metadata assets
//	@Description	Evaluates GetAllMetadataFromNetwork on the Fabric ledger and returns every stored metadata asset.
//	@Tags			metadata
//	@Produce		json
//	@Param			patient_id	query		string	false	"Filter by patient ID"
//	@Param			asset_id	query		string	false	"Filter by asset ID"
//	@Param			from		query		string	false	"Start date (created_at)"
//	@Param			to			query		string	false	"End date (created_at)"
//	@Success		200	{object}	utils.SuccessResponse{data=[]map[string]interface{}}
//	@Failure		500	{object}	utils.ErrorResponse
//	@Router			/metadata/ [get]
func GetAllMetadataHandler(contract *client.Contract, observer *MetadataObserver, elasticSvc *elasticsearch.ElasticService) gin.HandlerFunc {
	return func(c *gin.Context) {
		patientID := c.Query("patient_id")
		assetID := c.Query("asset_id")
		from := c.Query("from")
		to := c.Query("to")

		var mustClauses []map[string]interface{}

		if patientID != "" {
			mustClauses = append(mustClauses, map[string]interface{}{
				"match": map[string]interface{}{"patient_id": patientID},
			})
		}
		if assetID != "" {
			mustClauses = append(mustClauses, map[string]interface{}{
				"match": map[string]interface{}{"asset_id": assetID},
			})
		}

		if from != "" || to != "" {
			rangeQuery := map[string]interface{}{}
			if from != "" {
				rangeQuery["gte"] = from
			}
			if to != "" {
				rangeQuery["lte"] = to
			}
			mustClauses = append(mustClauses, map[string]interface{}{
				"range": map[string]interface{}{
					"created_at": rangeQuery,
				},
			})
		}

		// Filter out soft-deleted records in ES
		mustNotClauses := []map[string]interface{}{
			{
				"exists": map[string]interface{}{
					"field": "deleted_at",
				},
			},
		}

		query := map[string]interface{}{
			"query": map[string]interface{}{
				"bool": map[string]interface{}{
					"must":     mustClauses,
					"must_not": mustNotClauses,
				},
			},
		}

		results, err := elasticSvc.SearchDocuments(c.Request.Context(), "metadata", query)
		if err != nil {
			utils.SendError(c, http.StatusInternalServerError, "Failed to fetch metadata from search engine: "+err.Error())
			return
		}

		if observer != nil {
			observer.OnList(len(results))
		}

		utils.SendSuccess(c, "Metadata list retrieved successfully", results)
	}
}

// GetMetadataByIDHandler handles GET /api/metadata/:id
//
//	@Summary		Get metadata by ID
//	@Description	Evaluates GetMetadataById on the Fabric ledger and returns the matching metadata asset.
//	@Tags			metadata
//	@Produce		json
//	@Param			id	path		string	true	"Asset ID (numeric string, e.g. \"1\")"
//	@Success		200	{object}	utils.SuccessResponse{data=MetadataModel}
//	@Failure		400	{object}	utils.ErrorResponse
//	@Failure		500	{object}	utils.ErrorResponse
//	@Router			/metadata/{id} [get]
func GetMetadataByIDHandler(contract *client.Contract) gin.HandlerFunc {
	return func(c *gin.Context) {
		id := c.Param("id")
		if id == "" {
			utils.SendError(c, http.StatusBadRequest, "ID parameter is required")
			return
		}
		m, err := GetMetadataByID(contract, id)
		if err != nil {
			utils.SendError(c, http.StatusInternalServerError, err.Error())
			return
		}
		utils.SendSuccess(c, "Metadata retrieved successfully", m)
	}
}

// UpdateMetadataByIDHandler handles PUT /api/metadata/:id
//
//	@Summary		Update metadata by ID
//	@Description	Submits an UpdateMetadataById transaction to the Fabric ledger with the provided field values.
//	@Tags			metadata
//	@Accept			json
//	@Produce		json
//	@Param			id		path		string			true	"Asset ID (numeric string)"
//	@Param			metadata	body		MetadataModel	true	"Updated metadata fields"
//	@Success		200		{object}	utils.SuccessResponse{data=map[string]string}
//	@Failure		400		{object}	utils.ErrorResponse
//	@Failure		500		{object}	utils.ErrorResponse
//	@Router			/metadata/{id} [put]
func UpdateMetadataByIDHandler(contract *client.Contract, observer *MetadataObserver) gin.HandlerFunc {
	return func(c *gin.Context) {
		id := c.Param("id")
		if id == "" {
			utils.SendError(c, http.StatusBadRequest, "ID parameter is required")
			return
		}
		var req MetadataModel
		if err := c.ShouldBindJSON(&req); err != nil {
			utils.SendError(c, http.StatusBadRequest, "Invalid request body. Check the required fields and their types.")
			return
		}
		if err := UpdateMetadataByID(contract, id, req, observer); err != nil {
			utils.SendError(c, http.StatusInternalServerError, err.Error())
			return
		}
		utils.SendSuccess(c, "Metadata updated successfully", gin.H{"id": id})
	}
}

// DeleteMetadataByIDHandler handles DELETE /api/metadata/:id
//
//	@Summary		Delete metadata by ID
//	@Description	Submits a DeleteMetadataById transaction to the Fabric ledger, removing the asset permanently.
//	@Tags			metadata
//	@Produce		json
//	@Param			id	path		string	true	"Asset ID (numeric string)"
//	@Success		200	{object}	utils.SuccessResponse{data=map[string]string}
//	@Failure		400	{object}	utils.ErrorResponse
//	@Failure		500	{object}	utils.ErrorResponse
//	@Router			/metadata/{id} [delete]
func DeleteMetadataByIDHandler(contract *client.Contract, observer *MetadataObserver) gin.HandlerFunc {
	return func(c *gin.Context) {
		id := c.Param("id")
		if id == "" {
			utils.SendError(c, http.StatusBadRequest, "ID parameter is required")
			return
		}
		if err := DeleteMetadataByID(contract, id, observer); err != nil {
			utils.SendError(c, http.StatusInternalServerError, err.Error())
			return
		}
		utils.SendSuccess(c, "Metadata deleted successfully", gin.H{"id": id})
	}
}

// GetMetadataAuditoryByIDHandler handles GET /api/metadata/:id/auditory
//
//	@Summary		Get audit trail for a metadata asset
//	@Description	Returns the full immutable history of the asset from the audit service.
//	@Tags			metadata
//	@Produce		json
//	@Param			id	path		string	true	"Asset ID (numeric string)"
//	@Success		200	{object}	utils.SuccessResponse{data=[]audit.AuditModel}
//	@Failure		400	{object}	utils.ErrorResponse
//	@Router			/metadata/{id}/auditory [get]
func GetMetadataAuditoryByIDHandler(auditSvc *audit.AuditService) gin.HandlerFunc {
	return func(c *gin.Context) {
		id := c.Param("id")
		if id == "" {
			utils.SendError(c, http.StatusBadRequest, "ID parameter is required")
			return
		}
		
		history := auditSvc.GetByEntityID("Metadata", id)
		utils.SendSuccess(c, "Metadata audit trail retrieved successfully", history)
	}
}
