services:
  setup:
    container_name: fabric-setup
    build:
      context: .
      dockerfile: docker/Dockerfile.setup
    volumes:
      - .:/workspace  # Mapeia a pasta raiz do projeto para /workspace
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GOFLAGS=-buildvcs=false
    network_mode: "host"

  api:
    container_name: entruster-api
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    environment:
      - TEST_NETWORK_PATH=/app/fabric-samples/test-network
      - PEER_ENDPOINT=dns:///localhost:7051
      - PORT=8080
      - ELASTICSEARCH_URL=http://localhost:9200
    volumes:
      - ./fabric-samples:/app/fabric-samples
      - .:/app/shared          # Expõe a raiz para que o sentinela .fabric_ready seja visível
    network_mode: "host"
    restart: on-failure
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata: