// Package docs Code generated by swaggo/swag. DO NOT EDIT
package swaggerdocs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Silas Silva",
            "url": "https://github.com/silvasilas99/entruster"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/metadata/": {
            "get": {
                "description": "Evaluates GetAllMetadataFromNetwork on the Fabric ledger and returns every stored metadata asset.",
                "produces": ["application/json"],
                "tags": ["metadata"],
                "summary": "List all metadata assets",
                "parameters": [
                    {"type":"string","description":"Filter by patient ID","name":"patient_id","in":"query"},
                    {"type":"string","description":"Filter by asset ID","name":"asset_id","in":"query"},
                    {"type":"string","description":"Start date (created_at)","name":"from","in":"query"},
                    {"type":"string","description":"End date (created_at)","name":"to","in":"query"}
                ],
                "responses": {
                    "200": {"description":"OK","schema":{"allOf":[{"$ref":"#/definitions/utils.SuccessResponse"},{"type":"object","properties":{"data":{"type":"array","items":{"type":"object","additionalProperties":true}}}}]}},
                    "500": {"description":"Internal Server Error","schema":{"$ref":"#/definitions/utils.ErrorResponse"}}
                }
            },
            "post": {
                "description": "Submits a new metadata asset to the Hyperledger Fabric ledger. The asset ID is auto-generated by the chaincode.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["metadata"],
                "summary": "Register metadata on the blockchain",
                "parameters": [
                    {"description":"Metadata payload","name":"metadata","in":"body","required":true,"schema":{"$ref":"#/definitions/metadata.MetadataModel"}}
                ],
                "responses": {
                    "201": {"description":"Created","schema":{"allOf":[{"$ref":"#/definitions/utils.SuccessResponse"},{"type":"object","properties":{"data":{"type":"object","additionalProperties":{"type":"string"}}}}]}},
                    "400": {"description":"Bad Request","schema":{"$ref":"#/definitions/utils.ErrorResponse"}},
                    "500": {"description":"Internal Server Error","schema":{"$ref":"#/definitions/utils.ErrorResponse"}}
                }
            }
        },
        "/metadata/{id}": {
            "get": {
                "description": "Evaluates GetMetadataById on the Fabric ledger and returns the matching metadata asset.",
                "produces": ["application/json"],
                "tags": ["metadata"],
                "summary": "Get metadata by ID",
                "parameters": [{"type":"string","description":"Asset ID","name":"id","in":"path","required":true}],
                "responses": {
                    "200": {"description":"OK","schema":{"allOf":[{"$ref":"#/definitions/utils.SuccessResponse"},{"type":"object","properties":{"data":{"$ref":"#/definitions/metadata.MetadataModel"}}}]}},
                    "400": {"description":"Bad Request","schema":{"$ref":"#/definitions/utils.ErrorResponse"}},
                    "500": {"description":"Internal Server Error","schema":{"$ref":"#/definitions/utils.ErrorResponse"}}
                }
            },
            "put": {
                "description": "Submits an UpdateMetadataById transaction to the Fabric ledger.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["metadata"],
                "summary": "Update metadata by ID",
                "parameters": [
                    {"type":"string","description":"Asset ID","name":"id","in":"path","required":true},
                    {"description":"Updated metadata fields","name":"metadata","in":"body","required":true,"schema":{"$ref":"#/definitions/metadata.MetadataModel"}}
                ],
                "responses": {
                    "200": {"description":"OK","schema":{"allOf":[{"$ref":"#/definitions/utils.SuccessResponse"},{"type":"object","properties":{"data":{"type":"object","additionalProperties":{"type":"string"}}}}]}},
                    "400": {"description":"Bad Request","schema":{"$ref":"#/definitions/utils.ErrorResponse"}},
                    "500": {"description":"Internal Server Error","schema":{"$ref":"#/definitions/utils.ErrorResponse"}}
                }
            },
            "delete": {
                "description": "Submits a DeleteMetadataById transaction to the Fabric ledger.",
                "produces": ["application/json"],
                "tags": ["metadata"],
                "summary": "Delete metadata by ID",
                "parameters": [{"type":"string","description":"Asset ID","name":"id","in":"path","required":true}],
                "responses": {
                    "200": {"description":"OK","schema":{"allOf":[{"$ref":"#/definitions/utils.SuccessResponse"},{"type":"object","properties":{"data":{"type":"object","additionalProperties":{"type":"string"}}}}]}},
                    "400": {"description":"Bad Request","schema":{"$ref":"#/definitions/utils.ErrorResponse"}},
                    "500": {"description":"Internal Server Error","schema":{"$ref":"#/definitions/utils.ErrorResponse"}}
                }
            }
        },
        "/metadata/{id}/auditory": {
            "get": {
                "description": "Returns the full immutable history of the asset from the audit service.",
                "produces": ["application/json"],
                "tags": ["metadata"],
                "summary": "Get audit trail for a metadata asset",
                "parameters": [{"type":"string","description":"Asset ID","name":"id","in":"path","required":true}],
                "responses": {
                    "200": {"description":"OK","schema":{"allOf":[{"$ref":"#/definitions/utils.SuccessResponse"},{"type":"object","properties":{"data":{"type":"array","items":{"$ref":"#/definitions/audit.AuditModel"}}}}]}},
                    "400": {"description":"Bad Request","schema":{"$ref":"#/definitions/utils.ErrorResponse"}}
                }
            }
        },
        "/metadata/{id}/history": {
            "get": {
                "description": "Returns the Fabric ledger native transaction history for a metadata asset.",
                "produces": ["application/json"],
                "tags": ["metadata"],
                "summary": "Get blockchain history for a metadata asset",
                "parameters": [{"type":"string","description":"Asset ID","name":"id","in":"path","required":true}],
                "responses": {
                    "200": {"description":"OK","schema":{"allOf":[{"$ref":"#/definitions/utils.SuccessResponse"},{"type":"object","properties":{"data":{"type":"array","items":{"type":"object","additionalProperties":true}}}}]}},
                    "400": {"description":"Bad Request","schema":{"$ref":"#/definitions/utils.ErrorResponse"}}
                }
            }
        },
        "/thirdpartyappevent/": {
            "get": {
                "description": "Evaluates GetAllThirdPartyAppEventsFromNetwork on the Fabric ledger and returns every stored ThirdPartyAppEvent asset.",
                "produces": ["application/json"],
                "tags": ["thirdpartyappevent"],
                "summary": "List all ThirdPartyAppEvent assets",
                "parameters": [
                    {"type":"string","description":"Filter by app ID","name":"app_id","in":"query"},
                    {"type":"string","description":"Filter by event type","name":"event_type","in":"query"},
                    {"type":"string","description":"Start date (created_at)","name":"from","in":"query"},
                    {"type":"string","description":"End date (created_at)","name":"to","in":"query"}
                ],
                "responses": {
                    "200": {"description":"OK","schema":{"allOf":[{"$ref":"#/definitions/utils.SuccessResponse"},{"type":"object","properties":{"data":{"type":"array","items":{"type":"object","additionalProperties":true}}}}]}},
                    "500": {"description":"Internal Server Error","schema":{"$ref":"#/definitions/utils.ErrorResponse"}}
                }
            },
            "post": {
                "description": "Submits a new ThirdPartyAppEvent asset to the Hyperledger Fabric ledger. The asset ID is auto-generated by the chaincode.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["thirdpartyappevent"],
                "summary": "Register a ThirdPartyAppEvent on the blockchain",
                "parameters": [
                    {"description":"ThirdPartyAppEvent payload","name":"thirdpartyappevent","in":"body","required":true,"schema":{"$ref":"#/definitions/thirdpartyappevent.ThirdPartyAppEventModel"}}
                ],
                "responses": {
                    "201": {"description":"Created","schema":{"allOf":[{"$ref":"#/definitions/utils.SuccessResponse"},{"type":"object","properties":{"data":{"type":"object","additionalProperties":{"type":"string"}}}}]}},
                    "400": {"description":"Bad Request","schema":{"$ref":"#/definitions/utils.ErrorResponse"}},
                    "500": {"description":"Internal Server Error","schema":{"$ref":"#/definitions/utils.ErrorResponse"}}
                }
            }
        },
        "/thirdpartyappevent/{id}": {
            "get": {
                "description": "Evaluates GetThirdPartyAppEventById on the Fabric ledger and returns the matching asset.",
                "produces": ["application/json"],
                "tags": ["thirdpartyappevent"],
                "summary": "Get ThirdPartyAppEvent by ID",
                "parameters": [{"type":"string","description":"Asset ID","name":"id","in":"path","required":true}],
                "responses": {
                    "200": {"description":"OK","schema":{"allOf":[{"$ref":"#/definitions/utils.SuccessResponse"},{"type":"object","properties":{"data":{"$ref":"#/definitions/thirdpartyappevent.ThirdPartyAppEventModel"}}}]}},
                    "400": {"description":"Bad Request","schema":{"$ref":"#/definitions/utils.ErrorResponse"}},
                    "500": {"description":"Internal Server Error","schema":{"$ref":"#/definitions/utils.ErrorResponse"}}
                }
            },
            "put": {
                "description": "Submits an UpdateThirdPartyAppEventById transaction to the Fabric ledger.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["thirdpartyappevent"],
                "summary": "Update ThirdPartyAppEvent by ID",
                "parameters": [
                    {"type":"string","description":"Asset ID","name":"id","in":"path","required":true},
                    {"description":"Updated ThirdPartyAppEvent fields","name":"thirdpartyappevent","in":"body","required":true,"schema":{"$ref":"#/definitions/thirdpartyappevent.ThirdPartyAppEventModel"}}
                ],
                "responses": {
                    "200": {"description":"OK","schema":{"allOf":[{"$ref":"#/definitions/utils.SuccessResponse"},{"type":"object","properties":{"data":{"type":"object","additionalProperties":{"type":"string"}}}}]}},
                    "400": {"description":"Bad Request","schema":{"$ref":"#/definitions/utils.ErrorResponse"}},
                    "500": {"description":"Internal Server Error","schema":{"$ref":"#/definitions/utils.ErrorResponse"}}
                }
            },
            "delete": {
                "description": "Submits a DeleteThirdPartyAppEventById transaction to the Fabric ledger.",
                "produces": ["application/json"],
                "tags": ["thirdpartyappevent"],
                "summary": "Delete ThirdPartyAppEvent by ID",
                "parameters": [{"type":"string","description":"Asset ID","name":"id","in":"path","required":true}],
                "responses": {
                    "200": {"description":"OK","schema":{"allOf":[{"$ref":"#/definitions/utils.SuccessResponse"},{"type":"object","properties":{"data":{"type":"object","additionalProperties":{"type":"string"}}}}]}},
                    "400": {"description":"Bad Request","schema":{"$ref":"#/definitions/utils.ErrorResponse"}},
                    "500": {"description":"Internal Server Error","schema":{"$ref":"#/definitions/utils.ErrorResponse"}}
                }
            }
        },
        "/thirdpartyappevent/{id}/auditory": {
            "get": {
                "description": "Returns the full immutable history of the ThirdPartyAppEvent asset from the audit service.",
                "produces": ["application/json"],
                "tags": ["thirdpartyappevent"],
                "summary": "Get audit trail for a ThirdPartyAppEvent asset",
                "parameters": [{"type":"string","description":"Asset ID","name":"id","in":"path","required":true}],
                "responses": {
                    "200": {"description":"OK","schema":{"allOf":[{"$ref":"#/definitions/utils.SuccessResponse"},{"type":"object","properties":{"data":{"type":"array","items":{"$ref":"#/definitions/audit.AuditModel"}}}}]}},
                    "400": {"description":"Bad Request","schema":{"$ref":"#/definitions/utils.ErrorResponse"}}
                }
            }
        },
        "/thirdpartyappevent/{id}/history": {
            "get": {
                "description": "Returns the Fabric ledger native transaction history for a ThirdPartyAppEvent asset.",
                "produces": ["application/json"],
                "tags": ["thirdpartyappevent"],
                "summary": "Get blockchain history for a ThirdPartyAppEvent asset",
                "parameters": [{"type":"string","description":"Asset ID","name":"id","in":"path","required":true}],
                "responses": {
                    "200": {"description":"OK","schema":{"allOf":[{"$ref":"#/definitions/utils.SuccessResponse"},{"type":"object","properties":{"data":{"type":"array","items":{"type":"object","additionalProperties":true}}}}]}},
                    "400": {"description":"Bad Request","schema":{"$ref":"#/definitions/utils.ErrorResponse"}}
                }
            }
        },
        "/health/elasticsearch": {
            "get": {
                "description": "Returns the Elasticsearch cluster health status.",
                "produces": ["application/json"],
                "tags": ["health"],
                "summary": "Elasticsearch health check",
                "responses": {
                    "200": {"description":"OK","schema":{"allOf":[{"$ref":"#/definitions/utils.SuccessResponse"},{"type":"object","properties":{"data":{"type":"object","additionalProperties":true}}}]}},
                    "500": {"description":"Internal Server Error","schema":{"$ref":"#/definitions/utils.ErrorResponse"}}
                }
            }
        }
    },
    "definitions": {
        "audit.AuditAction": {
            "type": "string",
            "enum": ["CREATE","UPDATE","DELETE","LIST"],
            "x-enum-varnames": ["ActionCreate","ActionUpdate","ActionDelete","ActionList"]
        },
        "audit.AuditModel": {
            "type": "object",
            "properties": {
                "action": {"description":"Action is the operation performed (CREATE, UPDATE, DELETE, LIST).","allOf":[{"$ref":"#/definitions/audit.AuditAction"}]},
                "actor": {"description":"Actor is the identity that triggered the operation.","type":"string"},
                "details": {"description":"Details holds additional context about the operation.","type":"string"},
                "entity": {"description":"Entity identifies the domain object being audited.","type":"string"},
                "entity_id": {"description":"EntityID is the primary-key value of the affected record.","type":"string"},
                "id": {"description":"ID is an auto-incremented sequence number.","type":"integer"},
                "occurred_at": {"description":"OccurredAt is the UTC timestamp of when the operation was recorded.","type":"string"}
            }
        },
        "metadata.MetadataModel": {
            "type": "object",
            "properties": {
                "asset_id": {"type":"integer"},
                "created_at": {"description":"Stored as RFC3339 strings.","type":"string"},
                "created_by": {"type":"string"},
                "deleted_at": {"type":"string"},
                "deleted_by": {"type":"string"},
                "id": {"type":"integer"},
                "name": {"type":"string"},
                "source": {"type":"string"},
                "patient_id": {"type":"integer"},
                "rights": {"type":"string"},
                "terms_of_access": {"type":"string"},
                "updated_at": {"type":"string"},
                "updated_by": {"type":"string"},
                "value": {"type":"string"},
                "version": {"type":"string"},
                "category": {"type":"string"}
            }
        },
        "thirdpartyappevent.ThirdPartyAppEventModel": {
            "type": "object",
            "properties": {
                "id": {"description":"Auto-generated numeric ID.","type":"integer"},
                "app_id": {"description":"Identifier of the third-party application that emitted the event.","type":"string"},
                "event_type": {"description":"Categorical type of the event (e.g. USER_LOGIN, DATA_EXPORT).","type":"string"},
                "description": {"description":"Human-readable description of the event.","type":"string"},
                "event_data": {"description":"JSON-encoded payload with event-specific data.","type":"string"},
                "created_at": {"description":"RFC3339 timestamp of when the event was first recorded.","type":"string"},
                "updated_at": {"description":"RFC3339 timestamp of the last update.","type":"string"},
                "deleted_at": {"description":"RFC3339 timestamp of soft-deletion (null if active).","type":"string"},
                "created_by": {"description":"Identity that created the record.","type":"string"},
                "updated_by": {"description":"Identity that last updated the record.","type":"string"},
                "deleted_by": {"description":"Identity that deleted the record.","type":"string"}
            }
        },
        "utils.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {"type":"string","example":"An error occurred"},
                "success": {"type":"boolean","example":false}
            }
        },
        "utils.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {"type":"string","example":"Operation completed successfully"},
                "success": {"type":"boolean","example":true}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Entruster API",
	Description:      "REST API for registering and querying healthcare metadata and third-party app events on a Hyperledger Fabric blockchain.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
